import { Roboto } from 'next/font/google'

const roboto = Roboto({ 
  subsets: ['latin'],
  weight: ["100", "300" , "400", "500", "700", "900"]
 })

import './globals.css'
import Header from '@/components/Header'


export const metadata = {
  title: '2024 Operacijos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className} suppressHydrationWarning={true}>
        <main className="max-w-5xl m-auto p-4">
          <Header />
          {children}
        </main>
      </body>
    </html>
  )
}
